## Result枚举

```rust
enum Result<T, E> {
    Ok(T),
    Err(E),
}
```

处理一个Result

```rust
use std::fs::File;

fn main() {
    let f = File::open("hello.txt");
    let f = match f {
        Ok(file) => file,
        Err(error) => panic!("Problem opening the file: {:?}", error),
    }
}
```

## 匹配不同的错误

``` rust
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let f = File::open("hello.txt");
    let f = match f {
        Ok(file) => file,
        Err(error) => match error.kind() {
            ErrorKind::NotFound => {
                let create = File::create("hello.txt");
                match create {
                    Ok(fc) => fc,
                    Err(e) => {
                        panic!("create error,{}", e)
                    }
                }
            }
            other_error => {
                panic!("{}", other_error)
            }
        }
    };
}
```

## panic简写

match有时很冗长

Result<T, E>定义了辅助方法

unwrap：如果Result是Ok，unwrap会返回Ok，如果Result是Err，unwrap会为我们调用panic!

```rust
use std::fs::File;

fn main() {
    let file = File::open("hello.txt").unwrap();
}
```

expect()方法类似unwrap，但是有错误信息

```rust
use std::fs::File;

fn main() {
    let file = File::open("hello.txt").expect("Fail to open hello.txt");
}
```

## 传播错误

```rust
use std::array::from_mut;
use std::fs::File;
use std::io;
use std::io::Read;

fn main() {
    read_username_from_file().expect("错误");
}

fn read_username_from_file() -> Result<String, io::Error> {
    let f = File::open("hello.txt");

    let mut f = match f {
        Ok(file) => file,
        Err(e) => return Err(e),
    };

    let mut string = String::new();

    match f.read_to_string(&mut string) {
        Ok(_) => Ok(s),
        Err(e) => Err(e),
    }
}
```

### 传播错误的简写

```rust
use std::array::from_mut;
use std::fs::File;
use std::io;
use std::io::Read;

fn main() {
    read_username_from_file().expect("错误");
}

fn read_username_from_file() -> Result<String, io::Error> {
    let mut file = File::open("hello.txt")?;
    let mut string = String::new();
    file.read_to_string(&mut string)?;
    Ok(string)
}
```

可以使用链式调用进一步简化

```rust
use std::array::from_mut;
use std::fs::File;
use std::io;
use std::io::Read;

fn main() {
    read_username_from_file().expect("错误");
}

fn read_username_from_file() -> Result<String, io::Error> {
    let mut string = String::new();
    
    File::open("hello.txt")?.read_to_string(&mut string)?;
    Ok(string)
}
```

更简约的办法：

```rust
use std::{fs, io};

fn main() {
    read_username_from_file().expect("错误");
}

fn read_username_from_file() -> Result<String, io::Error> {
    fs::read_to_string("hello.txt")
}
```

## 哪里可以使用?运算符

在main中使用?会错误，main的返回值是()不是Result
```rust
use std::fs::File;

fn main() {
    let f = File::open("hello.txt")?;
}
```

只能在返回`Result`或者其他实现了`FromResidual`类型的函数中使用`?`运算符。

所以
1. 如果可以的话将函数返回值改为Result<T, E>
2. 使用`match`或`Result<T, E>`来处理Result

`?`符也可以用在`Option<T>`值，就和对`Result`使用`?`一样，如果None，函数提前退出，如果是Some，Some的值作为表达式的返回值。


`Box<dyn Error>`

```rust
use std::{fs, io};
use std::error::Error;
use std::fs::File;

fn main() -> Result<(),Box<dyn Error>>{
    let file = File::open("hello.txt")?;
    Ok(())
}
```

`Box<dyn Error>`是一个trait对象，可理解为任意类型的错误
